### ISSUE TITLE
Add Jen to waffle

### ISSUE THREAD

**Issue by Jorellana90** [Jorellana90/progressportal#18]
https://waffle.io/Jorellana90/progressportal/join

**Comment by jendiamond** [comment]
I can see you waffle board but I can't modify it because I am not a collaborator on the repository.

**Comment by jendiamond** [comment]
I can see your waffle board but I can't modify it because I am not a collaborator on your Github repository.
This is how to add me as a collaborator on Github.
1. Go to your github repo. Click on the "Settings" link
![Screen Shot 2019-02-23 at 10.33.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f06b7191a379ef0c2852415d4cbc30254d58eeb9cb74fce36f34985619e8826b0c20c46f19a4be8519b905ba218b4cd6bfe9894fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee14450a317326ae171326e0a.png)
2. Click on the "Collaborators" link in the right sidebar
![Screen Shot 2019-02-23 at 10.33.40 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f06b7191a379ef0c2852415b4ebc30254d58eeb9cb74fce36f34985619e8826b0c20c46f19a4be8519b905ba218b4cd6bfe9894fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee14450a3163166e371356e0a.png)
3. Type inn my github user name which is jendiamond then Click the "Add as Collaborator" button
![Screen Shot 2019-02-23 at 10.34.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f06b7191a379ef0c2855415b49bc30254d58eeb9cb74fce36f34985619e8826b0c20c46f19a4be8519b905ba218b4cd6bfe9894fc3fa2137a5dad11b61435c52dcbd4f3fb2984dc259f34ee14450a3153561e176356e0a.png)
